### ISSUE TITLE
Error In Execution

### ISSUE THREAD

**Issue by JoelitonMods** [tien0246/Il2CppDumper-for-COD#1]
I'm running it but it doesn't work in .exe, I click and it doesn't do anything, could you explain how to use it?

**Comment by tien0246** [comment]
Download and install NET 7
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.20-windows-x64-installer

**Comment by JoelitonMods** [comment]
> Baixe e instale o NET 7 https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.20-windows-x64-installer

it worked thanks bro

**Comment by aQReh** [comment]
Thanks worked
